export const GETDATAREQUEST="GETDATAREQUEST";
export const GETDATASUCCESS="GETDATASUCCESS";
export const GETDATAERROR="GETDATAERROR";

export const UPDATEDATAREQUEST="UPDATEDATAREQUEST";
export const UPDATEDATASUCCESS="UPDATEDATASUCCESS";

export const UPDATEDATAERROR="UPDATEDATAERROR";
