export const LOGINREQUEST="LOGINREQUEST";
export const LOGINSUCCESS="LOGINSUCCESS";
export const LOGINERROR="LOGINERROR";
export const REGISTERREQUEST="REGISTERREQUEST";
export const REGISTERSUCCESS="REGISTERSUCCESS";
export const REGISTERERROR="REGISTERERROR";

export const LOGOUT="LOGOUT"