export const POSTDATAREQUEST ="POSTDATAREQUEST";
export const POSTDATASUCCESS ="POSTDATASUCCESS";
export const POSTDATAERROR ="POSTDATAERROR";

export const GETCARTDATAREQUEST="GETCARTDATAREQUEST";
export const GETCARTDATASUCCESS="GETCARTDATASUCCESS";
export const GETCARTDATAERROR="GETCARTDATAERROR";

export const DELETECARTDATAREQUEST="DELETEDATAREQUEST";
export const DELETECARTDATASUCCESS="DELETEDATASUCCESS";
export const DELETECARTDATAERROR="DELETEDATAERROR";

export const UPDATECARTDATAREQUEST="UPDATEDATAREQUEST";
export const UPDATECARTDATASUCCESS="UPDATEDATASUCCESS";
export const UPDATECARTDATAERROR="UPDATEDATAERROR";
